name: Health Monitor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  health-check:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up PowerShell
      uses: actions/setup-powershell@v1
      with:
        powershell-version: '7.0'
    
    - name: Install Chocolatey
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    
    - name: Install Required Tools
      shell: pwsh
      run: |
        choco install php composer nodejs-lts jq gh -y
        refreshenv
    
    - name: Configure GitHub CLI
      shell: pwsh
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
    
    - name: Run Health Checks
      shell: pwsh
      run: |
        .\.health\tests\run-tests.ps1 -Categories System,GitHub,Services -AutoHeal
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: health-check-results
        path: .health/logs/test-results-*.json
    
    - name: Upload Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: health-check-logs
        path: .health/logs/

  deploy:
    needs: health-check
    if: github.ref == 'refs/heads/main' && success()
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up PowerShell
      uses: actions/setup-powershell@v1
      with:
        powershell-version: '7.0'
    
    - name: Configure GitHub CLI
      shell: pwsh
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
    
    - name: Deploy to GitHub
      shell: pwsh
      run: |
        .\.health\utils\github.ps1
        Start-GitHubDeploy -Branch main -Environment production -Variables @{
          VERSION = "${{ github.sha }}"
          TIMESTAMP = "${{ github.event.repository.updated_at }}"
        } 